name: API Tests CI

on:
  push:
    branches:
      - main

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run API tests with report generation
        run: |
          mkdir -p test-reports
          pytest tests/ --junitxml=test-reports/results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: test-reports/results.xml
