name: API Tests CI

on:
  push:
    branches:
      - main

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-html

      - name: Run API tests with HTML report generation
        run: |
          mkdir -p test-reports
          pytest tests/ --html=test-reports/report.html --self-contained-html

      - name: Upload HTML test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: test-reports/report.html